apiVersion: batch/v1
kind: Job
metadata:
  name: ci-metrics-job
  namespace: monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: metrics
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Pushing Frontend CI/CD metrics"

              PUSHGATEWAY_URL="http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091"

              echo "ci_deploy_status{env=\"{{ENV}}\",service=\"frontend\"} {{STATUS}}" | curl --data-binary @- \
              ${PUSHGATEWAY_URL}/metrics/job/frontend_status/env/{{ENV}}

              echo "ci_deploy_event{env=\"{{ENV}}\",service=\"frontend\",run_id=\"{{RUN_ID}}\"} 1" | curl --data-binary @- \
              ${PUSHGATEWAY_URL}/metrics/job/frontend_event/run_id/{{RUN_ID}}/env/{{ENV}}

              echo "Frontend metrics pushed successfully"
