apiVersion: batch/v1
kind: Job
metadata:
  name: ci-metrics-job
  namespace: monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: metrics
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Pushing CI/CD metrics to Pushgateway"

              # Latest deployment status
              echo "ci_deploy_status{env=\"{{ENV}}\",service=\"{{SERVICE}}\"} {{STATUS}}" | curl --data-binary @- \
              http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics/job/{{SERVICE}}_status

              # Deployment event for correct count
              echo "ci_deploy_event{env=\"{{ENV}}\",service=\"{{SERVICE}}\",run_id=\"{{RUN_ID}}\"} 1" | curl --data-binary @- \
              http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics/job/{{SERVICE}}_event

              echo "Metrics pushed successfully"
