name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npm test -- --watchAll=false --passWithNoTests
      - run: CI=false npm run build

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.DEMOAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMOAPP_REGISTRY_PASSWORD }}

      - name: Build & Push Image
        id: set-image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.run_id }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOAPP_AZURE_CREDENTIALS }}

      - run: az aks get-credentials --resource-group project-demo --name projectaks

      - name: Deploy DEV
        run: |
          IMAGE=${{ needs.build.outputs.image }}
          sed -i "s|image: nginx|image: $IMAGE|g" k8s/dev/deployment.yaml
          kubectl apply -f k8s/dev/

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: stage

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOAPP_AZURE_CREDENTIALS }}

      - run: az aks get-credentials --resource-group project-demo --name projectaks

      - name: Deploy STAGE
        run: |
          IMAGE=${{ needs.build.outputs.image }}
          sed -i "s|image: nginx|image: $IMAGE|g" k8s/stage/deployment.yaml
          kubectl apply -f k8s/stage/

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: prod   # 👈 approval here

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOAPP_AZURE_CREDENTIALS }}

      - run: az aks get-credentials --resource-group project-demo --name projectaks

      - name: Deploy PROD
        run: |
          IMAGE=${{ needs.build.outputs.image }}
          sed -i "s|image: nginx|image: $IMAGE|g" k8s/prod/deployment.yaml
          kubectl apply -f k8s/prod/
